[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "piper_teleop"
version = "1.0.0"
description = "Teleoperation, data recording, and policy deployment for a single the AgileX Piper arm"
authors = [
    {name = "Zeno Hamers", email = "zeno@tactilerobotics.ai"},
    {name = "Alex Spiridonov", email = "alex@tactilerobotics.ai"},
    {name = "Sebastien Steininger", email = "sebastien.devmail@gmail.com"},
]
keywords = ["robotics", "teleoperation", "robot-control"]

dependencies = [
    "opencv-python",
    "pyrealsense2",
    "pygame>=2.5",
    "PyYAML",
    "meshcat",
    "piper_sdk==0.3.3",
    "lerobot",
]

requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
]

[project.scripts]
robotserver = "piper_teleop.robot_server.main:main_cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 120
